### ISSUE TITLE
error using test.py

### ISSUE THREAD

**Issue by bat3a** [xieenze/PolarMask#14]
hi

i get this error when trying to use tools\test.py:
`PolarMask$ python tools/test.py demo/polar_r101.py demo/r101_1x.pth --show 
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[                              ] 0/192, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/test.py", line 224, in <module>
    main()
  File "tools/test.py", line 184, in main
    outputs = single_gpu_test(model, data_loader, args.show)
  File "tools/test.py", line 26, in single_gpu_test
    result = model(return_loss=False, rescale=not show, **data)
  File "/home/me/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/me/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/me/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/me/Desktop/PolarMask/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/me/Desktop/PolarMask/mmdet/models/detectors/base.py", line 88, in forward
    return self.forward_test(img, img_meta, **kwargs)
  File "/home/me/Desktop/PolarMask/mmdet/models/detectors/base.py", line 79, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/me/Desktop/PolarMask/mmdet/models/detectors/polarmask.py", line 65, in simple_test
    bbox_list = self.bbox_head.get_bboxes(*bbox_inputs)
  File "/home/me/Desktop/PolarMask/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/home/me/Desktop/PolarMask/mmdet/models/anchor_heads/polarmask_head.py", line 403, in get_bboxes
    scale_factor, cfg, rescale)
  File "/home/me/Desktop/PolarMask/mmdet/models/anchor_heads/polarmask_head.py", line 480, in get_bboxes_single
    _mlvl_bboxes,
UnboundLocalError: local variable '_mlvl_bboxes' referenced before assignment
`

please note that:
- i can inference successfully using the demo/inference_demo.ipynb
- i am using my own coco dataset and i added the mydataset.py:

from .coco import CocoDataset
from .registry import DATASETS
@DATASETS.register_module
class FishesDataset(CocoDataset):
    CLASSES = ('fish')
and imported it in __init__ with:
from .fishes import FishesDataset

-i am using this config file 
[polar_r101_py.txt](https://github.com/xieenze/PolarMask/files/3936165/polar_r101_py.txt)

**Comment by bat3a** [comment]
the problem was in the annotation file, it is now fixed.

**Comment by zack624** [comment]
> the problem was in the annotation file, it is now fixed.

Hi, could you please introduce the solution in detail.

**Comment by JosephTech** [comment]
> > the problem was in the annotation file, it is now fixed.
> 
> Hi, could you please introduce the solution in detail.


python tools/test.py configs/polarmask/4gpu/polar_768_1x_r50.py work_dirs/trash/epoch_12.pth --out /mnt/lxr/Polarmask/PolarMaskmaster/work_dirs/out/results.pkl

**don't use ‘--show’**，

because default show=False in   test.py/single_gpu_test()，

and 'rescale=not show' in this function，it means 'rescale=True'

'rescale=True' will be used in mmdet/models/anchor_heads/polarmask_head.py
