### ISSUE TITLE
Dimension out of range (expected to be in range of [-2, 1], but got 2)

### ISSUE THREAD

**Issue by HouHou0925** [xieenze/PolarMask#24]
您好
我是使用自己的數據集 只有分兩類
但是在訓練時一直出現這個錯誤

flatten_bbox_preds: torch.Size([40920, 4])
flatten_mask_targets: torch.Size([40920])
points: torch.Size([2804, 2])
distance: torch.Size([2804, 4])
points: torch.Size([2804, 2])
distance: torch.Size([2804, 4])
pred: torch.Size([2804, 36])
target: torch.Size([2804])

Traceback (most recent call last):
  File "tools/train.py", line 154, in <module>
    main()
  File "tools/train.py", line 123, in main
    logger=logger)
  File "/home/Hou/PolarMask/mmdet/apis/train.py", line 60, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/Hou/PolarMask/mmdet/apis/train.py", line 221, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/usr/local/lib/python3.5/dist-packages/mmcv/runner/runner.py", line 359, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/mmcv/runner/runner.py", line 263, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/home/Hou/PolarMask/mmdet/apis/train.py", line 38, in batch_processor
    losses = model(**data)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/Hou/PolarMask/mmdet/core/fp16/decorators.py", line 49, in new_func
    return old_func(*args, **kwargs)
  File "/home/Hou/PolarMask/mmdet/models/detectors/base.py", line 86, in forward
    return self.forward_train(img, img_meta, **kwargs)
  File "/home/Hou/PolarMask/mmdet/models/detectors/polarmask.py", line 55, in forward_train
    extra_data=extra_data
  File "/home/Hou/PolarMask/mmdet/core/fp16/decorators.py", line 127, in new_func
    return old_func(*args, **kwargs)
  File "/home/Hou/PolarMask/mmdet/models/anchor_heads/polarmask_head.py", line 289, in loss
    avg_factor=pos_centerness_targets.sum())
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/Hou/PolarMask/mmdet/models/losses/mask_iou_loss.py", line 23, in forward
    total = torch.stack([pred,target], -1)
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

我有把pred 和 target 印出來看看
不知道為什麼我的 target 只有一維 
flatten_mask_targets 也是 應該要是[x,36]
(有時會會有二維 但不是[x,36]  而是像 target: torch.Size([34, 4]))

這種情況不一定每次都出現  可能訓練到一半才出現 或是一開始就出現
不知道您有沒有遇過類似的問題能夠幫忙解決 感謝

**Comment by xieenze** [comment]
I do not try on other private dataset, so I can not help you. 😁

**Comment by HouHou0925** [comment]
i use the cocodataset  have the same problem

**Comment by HouHou0925** [comment]
ok 我找到問題了
in polarmask_head.py    line:359

labels_list, bbox_targets_list, mask_targets_list = extra_data.values()

extra_data.values()  的返回順序每次都不同 
也許是python 版本上的差異

labels_list = extra_data['_gt_labels']
bbox_targets_list = extra_data['_gt_bboxes']
mask_targets_list = extra_data['_gt_masks']

改成這樣就ok了^_^
