### ISSUE TITLE
IndexError: Caught IndexError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by SakuBorder** [xieenze/PolarMask#55]
Traceback (most recent call last):
  File "./tools/train.py", line 163, in <module>
    main()
  File "./tools/train.py", line 124, in main
    logger=logger)
  File "/home/reddot/PolarMask-master/mmdet/apis/train.py", line 65, in train_detector
    _non_dist_train(model, dataset, cfg, validate=validate)
  File "/home/reddot/PolarMask-master/mmdet/apis/train.py", line 228, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 384, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/runner.py", line 279, in train
    for i, data_batch in enumerate(data_loader):
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/reddot/PolarMask-master/mmdet/datasets/coco_seg.py", line 582, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/reddot/PolarMask-master/mmdet/datasets/coco_seg.py", line 200, in prepare_train_img
    ann = self.get_ann_info(idx)
  File "/home/reddot/PolarMask-master/mmdet/datasets/coco_seg.py", line 76, in get_ann_info
    return self._parse_ann_info(ann_info, self.with_mask)
  File "/home/reddot/PolarMask-master/mmdet/datasets/coco_seg.py", line 127, in _parse_ann_info
    if ann['area'] <= 15 or (w < 10 and h < 10) or self.coco.annToMask(ann).sum() < 15:
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 439, in annToMask
    rle = self.annToRLE(ann)
  File "/root/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/pycocotools-2.0-py3.7-linux-x86_64.egg/pycocotools/coco.py", line 424, in annToRLE
    rles = maskUtils.frPyObjects(segm, h, w)
  File "pycocotools/_mask.pyx", line 292, in pycocotools._mask.frPyObjects
IndexError: list index out of range

**Comment by WenzheShi** [comment]
Hi, I'm getting the same error, is there any solution?
