### ISSUE TITLE
ModuleNotFoundError: No module named 'mmdet.version'

### ISSUE THREAD

**Issue by ty199931** [xieenze/PolarMask#65]
When I run the demo, it appear:
Traceback (most recent call last):
  File "/home/ty/下载/PolarMask-master/demo/demo.py", line 1, in <module>
    from mmdet.apis import init_detector, inference_detector, show_result_pyplot, show_result
  File "/home/ty/下载/PolarMask-master/mmdet/__init__.py", line 1, in <module>
    from .version import __version__, short_version
ModuleNotFoundError: No module named 'mmdet.version'

And I have compiled the mmdetection,But it doesn't work.
Please help me!

**Comment by li-fz** [comment]
Do you save the problem?I have the same error

**Comment by ty199931** [comment]
I can not solve it,so I change a new model



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月3日(星期五) 中午1:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xieenze/PolarMask] ModuleNotFoundError: No module named &#39;mmdet.version&#39; (#65)





 
Do you save the problem?I have the same error
