### ISSUE TITLE
'PolarMask is not in the models registry'

### ISSUE THREAD

**Issue by Litao917** [xieenze/PolarMask#66]
Hi @xieenze , 

We followed the installation guide and the action you suggested in issue #32. 
But we still met a similar error:  'PolarMask is not in the models registry'.
What is the problem ? 

Thanks

**Comment by Litao917** [comment]
Log info:

`2021-08-30 17:48:00,915 - mmdet - INFO - Distributed training: False
/home/arl/anaconda3/envs/open_mmlab/lib/python3.7/site-packages/mmdet/models/builder.py:52: UserWarning: train_cfg and test_cfg is deprecated, please specify them in model
  'please specify them in model', UserWarning)
Traceback (most recent call last):
  File "tools/train.py", line 149, in <module>
    main()
  File "tools/train.py", line 98, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/arl/anaconda3/envs/open_mmlab/lib/python3.7/site-packages/mmdet/models/builder.py", line 58, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/arl/anaconda3/envs/open_mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 210, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/arl/anaconda3/envs/open_mmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 26, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/arl/anaconda3/envs/open_mmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'PolarMask is not in the models registry'`

**Comment by whksyjs2021** [comment]
same problem

**Comment by GrayinChina** [comment]
+1

**Comment by Glaciercoool** [comment]
i need help too，it confusing me a lot
